name: CI/CD Pipeline for Kvitka Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t faistudio/kvitka-backend:latest .
        docker push faistudio/kvitka-backend:latest

    - name: Run Docker Container
      run: |
        docker run -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} faistudio/kvitka-backend

  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Python Environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Run Tests
    - name: Run Tests
      run: |
        python -m unittest discover -s tests
