name: GCP Authentication
on: [push]

jobs:
  auth:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for Workload Identity Federation
    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Authenticate with Google Cloud using Workload Identity Federation
      - id: gcp-auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/891197171034/locations/global/workloadIdentityPools/github-pool/providers/github"
          service_account: "artintel-api-service@fm8ai-438912.iam.gserviceaccount.com"
          # Optionally, provide credentials directly via JSON
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      # Step 3: Verify authentication with gcloud
      - name: Verify Authentication
        run: gcloud auth list

      # Add other build or deploy steps here, as required for your project
