name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Authenticate to Google Cloud
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/743235832629/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github@my-project-68184-1726215596188.iam.gserviceaccount.com

    # Step 3: Configure Docker for Google Cloud
    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    # Step 4: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t europe-west1-docker.pkg.dev/my-project-68184-1726215596188/kvitka-subproject:latest ./src/subproject
        docker push europe-west1-docker.pkg.dev/my-project-68184-1726215596188/kvitka-subproject:latest

    # Step 5: Deploy to Google Cloud Run
    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy kvitka-subproject \
          --image europe-west1-docker.pkg.dev/my-project-68184-1726215596188/kvitka-subproject:latest \
          --platform managed \
       
