name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/kvitka-chatbot:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/kvitka-chatbot:latest

    # Step 4: Deploy (Optional)
    # Add deployment steps here if you're deploying to a specific platform like Render or Railway.

  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Python Environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Run Tests
    - name: Run Tests
      run: |
        python -m unittest discover -s tests
