name: CI/CD Pipeline for Kvitka Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read
      id-token: write  # Required for OIDC

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Google Credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > src\config\clientLibraryConfig-github.json


      # Step 2: Authenticate with Google Cloud using Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: your-project-id

      # Step 4: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 6: Run Unit Tests
      - name: Run Unit Tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest tests/test_app.py

      # Step 7: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t faistudio/kvitka-backend:${{ github.sha }} .
          docker push faistudio/kvitka-backend:${{ github.sha }}

      # Step 9: Deploy to Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy kvitka-backend \
            --image faistudio/kvitka-backend:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
