name: CI/CD Pipeline for Kvitka Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Run tests
    - name: Run Unit Tests
      run: |
        pytest tests/test_app.py

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t faistudio/kvitka-backend .

    # Push Docker Image
    - name: Push Docker Image
      run: |
        docker push faistudio/kvitka-backend

    # Deploy to Google Cloud Run
    - name: Deploy to Google Cloud Run
      run: |
        gcloud auth configure-docker
        gcloud run deploy kvitka-backend \
          --image faistudio/kvitka-backend:latest \
          --platform managed \
          --region us-central1 \
          --set-env-vars OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
