name: GCP Authentication and Google Drive Token Generation

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  generate_bearer_token:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for Workload Identity Federation

    steps:
      # Step 1: Authenticate with Google Cloud using Workload Identity Federation
      - id: gcp-auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: "fm8ai-438912"
          workload_identity_provider: "projects/891197171034/locations/global/workloadIdentityPools/github-pool/providers/github"
          service_account: "artintel-api-service@fm8ai-438912.iam.gserviceaccount.com"

      # Step 2: Verify authentication with gcloud (optional, for debugging purposes)
      - name: Verify Authentication
        run: gcloud auth list

      # Step 3: Generate and store the Bearer token
      - name: Generate Google Cloud Access Token
        id: generate_token
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV
