name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/subproject/requirements.txt

    # Step 4: Run Unit Tests
    - name: Run Unit Tests
      run: |
        pytest tests/

  docker-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t your-dockerhub-username/kvitka-subproject:latest ./src/subproject
        docker push your-dockerhub-username/kvitka-subproject:latest

    # Step 4: Deploy to Google Cloud Run
    - name: Deploy to Google Cloud Run
      run: |
        gcloud auth activate-service-account --key-file=${{ secrets.GCLOUD_KEY }}
        gcloud config set project your-google-cloud-project
        gcloud run deploy kvitka-subproject \
          --image docker.io/your-dockerhub-username/kvitka-subproject:latest \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated

